export const TEAM2ABB = {
  'Atlanta Hawks'                    :'ATL', 
  'Brooklyn Nets'                    :'BRK',
  'Boston Celtics'                   :'BOS', 
  'Charlotte Hornets'                :'CHO', 
  'Chicago Bulls'                    :'CHI', 
  'Cleveland Cavaliers'              :'CLE', 
  'Dallas Mavericks'                 :'DAL', 
  'Denver Nuggets'                   :'DEN', 
  'Detroit Pistons'                  :'DET', 
  'Golden State Warriors'            :'GOS', 
  'Golden State Warriors'            :'GSW', 
  'Houston Rockets'                  :'HOU', 
  'Indiana Pacers'                   :'IND', 
  'Los Angeles Clippers'             :'LAC', 
  'Los Angeles Lakers'               :'LAL', 
  'Memphis Grizzlies'                :'MEM', 
  'Miami Heat'                       :'MIA', 
  'Milwaukee Bucks'                  :'MIL', 
  'Minnesota Timberwolves'           :'MIN', 
  'New Jersey Nets'                  :'NJN', 
  'New Orleans Hornets'              :'NOH', 
  'New Orleans/Oklahoma City Hornets':'NOK', 
  'New Orleans Pelicans'             :'NOP', 
  'New York Knicks'                  :'NYK', 
  'Oklahoma City Thunder'            :'OKC', 
  'Orlando Magic'                    :'ORL', 
  'Philadelphia 76ers'               :'PHI', 
  'Portland Trail Blazers'           :'POR', 
  'Phoenix Suns'                     :'PHX', 
  'Sacramento Kings'                 :'SAC', 
  'San Antonio Spurs'                :'SAN', 
  'San Antonio Spurs'                :'SAS', 
  'Seattle SuperSonics'              :'SEA', 
  'Toronto Raptors'                  :'TOR', 
  'Utah Jazz'                        :'UTA', 
  'Vancouver Grizzlies'              :'VAN', 
  'Washington Wizards'               :'WAS'}